services:
  db:
    image: postgres:15
    container_name: myproject_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=myproject_db
      - POSTGRES_USER=myproject_user
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myproject_user -d myproject_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    container_name: myproject_django
    # command: python manage.py runserver 0.0.0.0:8000
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate"

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=myproject_db
      - DB_USER=myproject_user
      - DB_PASSWORD=123
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: